(function(r){function w(){}function m(b,t,a,c){this.M=new Date;this.T=b;this.H=a||[];this.L=c||null;this.level=t;this.H=JSON.parse(JSON.stringify(this.H))}function n(){this.s=[]}function c(b){this.b=b;this.v=b.getSlotElementId();this.B=b.getAdUnitPath();this.Y=b.getSlotId().getId();this.G="/"!=this.B.charAt(0)?"/"+this.B.toString():this.B.toString();this.A=[this.G,this.v].join("|");this.u=b.getOutOfPage();this.j=null;this.l=!1;this.I=[];this.w=[];this.i=!1;this.m={fetched:0,rendered:0,bidRequests:0,
bids:0,refresh:0,display:0};this.c=this.o=!1;this.X()}function x(){var b="SB"+(new Date).getTime().toString()+Math.floor(1E5*Math.random());return"function"===typeof window[b]?x():b}function e(){this.b=[];this.i={};this.j={};this.l=[];this.B=this.h=null;this.c=new n;this.o={};this.C=[];this.da=[]}var v={log:1,warn:3,error:5};m.prototype.getType=function(){return this.T};m.prototype.getSlot=function(){return this.L};m.prototype.getMessageArgs=function(){return this.H};m.prototype.getTimestamp=function(){return this.M};
m.prototype.toObject=function(){return{ts:this.M,typeId:this.T,messageArgs:this.H,slot:this.L?this.L.toObject():null,level:this.level}};m.prototype.getLevel=function(){return this.level};n.prototype.log=function(b,t,a){b=new m(b,v.log,t,a);this.s.push(b)};n.prototype.warn=function(b,t,a){b=new m(b,v.warn,t,a);this.s.push(b)};n.prototype.error=function(b,t,a){b=new m(b,v.error,t,a);this.s.push(b)};n.prototype.getLogs=function(){return this.s};n.prototype.getLogBySlot=function(b){var a=[];b="object"===
typeof b?b.getElementID():b+"";for(var d=0;d<this.s.length;d++){var c=this.s[d],f=c.getSlot();f&&f.getElementID()===b&&a.push(c)}return a};n.prototype.getLogsSimple=function(){return this.s.map(function(b){return b.toObject()})};n.prototype.getSlotLogsSimple=function(b){return this.getLogBySlot(b).map(function(b){return b.toObject()})};c.log=function(b,a,d){w(b,a,d)};c.b=function(){};c.setLogger=function(b){w=b};c.c=[];c.acceptedSizes=function(b){return 1===arguments.length?(c.c=b,c):c.c};c.setDisplay=
function(b){c.b=b};c.prototype.X=function(){var b=this,a=this.b;a.getMorpheusSlot=function(){return b};var d=a.fetchStarted;a.fetchStarted=function(f){d.apply(a,arguments);c.log(10,["fetchStarted"],b)};var g=a.fetchEnded;a.fetchEnded=function(){b.m.fetched++;c.log(10,["fetchEnded"],b);g.apply(a,arguments);b.c=!1}};c.prototype.V=function(){return this.b.getTargetingMap()};c.prototype.F=function(b){var a={};"object"===typeof b?a=b:a[b]=void 0;for(var d in a)this.b.setTargeting(d,a[d])};c.prototype.O=
function(b){var a=this.V(),d={},g=!1;if("function"===typeof b)for(var f in a)b(f,a[f])?g=!0:d[f]=a[f];else g=!0;g&&(c.log(24,[this.getKeymakerKey()],this),this.b.clearTargeting(),this.F(d))};c.prototype.N=function(){this.O(function(b){return"sbi_"===b.substr(0,4)});this.c=!1;c.log(14,[this.getKeymakerKey()],this)};c.prototype.display=function(){0===this.m.display++?(c.log(15,[this.getKeymakerKey()],this),c.b(this.v)):c.log(25,[this.getKeymakerKey()],this)};c.prototype.J=function(b){b=b||!1;if(this.u)return[];
for(var a="",d=[],g=this.b.getSizes(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight),f=0;f<g.length;f++)a=g[f],(a="object"!==typeof a?!1:[a.getWidth(),a.getHeight()])&&(b||-1!=c.acceptedSizes().indexOf(a.join("x")))&&d.push(a);return d};c.prototype.U=function(){return this.C().join(",")};c.prototype.C=function(b){var a=[];this.u||this.l?a=[]:this.j&&0<this.j.length?a=this.j.map(function(b){return b.join("x")}):
a=this.J(b);return a.map(function(b){return b.join("x")})};c.prototype.W=function(){return this.l||this.c||this.i?!1:0<this.C().length};c.prototype.isUnfetched=function(){return!this.o&&!this.i};c.prototype.getElementID=function(){return this.v};c.prototype.getKeymakerKey=function(){return this.A};c.prototype.setBid=function(b){this.w.push({M:new Date,ea:b});this.F(b);b.hasOwnProperty("sbi_aid")?(this.I.push(b.sbi_aid),this.m.bids++,c.log(13,[this.getKeymakerKey(),b],this),b.hasOwnProperty("sbi_dozer")&&
c.log(27,[this.getKeymakerKey(),b],this)):c.log(26,[this.getKeymakerKey()],this);this.c=!0;this.i=!1;return this};c.prototype.addToRequestIfNeeded=function(b){this.o=!0;this.W()&&(this.N(),this.i=!0,this.m.bidRequests++,b[this.A]=this.U());return this.v};c.prototype.getSlot=function(){return this.b};c.prototype.getCounts=function(){return this.m};c.prototype.getHistory=function(){return this.w};c.prototype.toObject=function(){return{initialChecked:this.o,counts:this.m,history:this.w,elementID:this.v,
keyMakerKey:this.A,adUnitPath:this.G,isOutOfPage:this.u,sizesOverride:this.j,disabledOverride:this.l,sizes:this.C(!0),slotId:this.Y}};c.prototype.getOutOfPage=function(){return this.u};c.prototype.getBidSet=function(){return this.c};c.prototype.getBidding=function(){return this.i};c.prototype.setSizes=function(b){this.j=b;c.log(40,[this.getKeymakerKey(),b],this);return this};c.prototype.disable=function(){this.l=!0;c.log(42,[this.getKeymakerKey()],this);return this};c.prototype.getInitialChecked=
function(){return this.o};e.prototype.addSlot=function(b){b=new c(b);var a=b.getElementID();this.i[a]=this.j[b.getKeymakerKey()]=b;this.b.push(b);b.getOutOfPage()?this.c.log(36,[b.getKeymakerKey()],b):this.c.log(11,[b.getKeymakerKey()],b);this.o.hasOwnProperty(a)&&b.setSizes(this.o[a]);-1!==this.C.indexOf(a)&&b.disable();return b};e.prototype.I=function(b,a){var d=this.w(b);d?d.setBid(a):this.c.log(21,[b])};e.prototype.getBidsForUnfetched=function(b){var a=this;"function"===!typeof b&&(b=function(){});
this.c.log(22,[]);for(var d=[],g=0;g<a.b.length;g++)a.b[g].isUnfetched()&&d.push(a.b[g]);a.F(d,function(){var d=a.l;a.l=[];for(var g=0;g<d.length;g++){var h=d[g];if("object"===typeof h){var e=h.getCounts();h.getInitialChecked()&&!h.getBidding()?1>e.display&&h.display():a.l.push(h)}else c.b(h)}b()})};e.prototype.F=function(b,a){var d={};b.map(function(b){return b.addToRequestIfNeeded(d)});this.c.log(23,[d]);this.J(d,a)};e.prototype.N=function(b){this.h.setTargeting("sbi_dc",b)};e.prototype.initialize=
function(b,a){this.B=b;this.h=b.pubads();e.setLogger(this.c);c.setDisplay(this.B.display);c.acceptedSizes(a)};e.prototype.O=function(b){this.N(b)};e.prototype.J=function(b,a){var d=this;if("object"===typeof b&&0<Object.keys(b).length){var c=x(),f=!1;window[c]=function(c){if(!f){d.O(c.sbi_dc);for(var g in c.slots)d.I(g,c.slots[g]);a(b)}};var e="//apex.go.sonobi.com/trinity.js?key_maker="+JSON.stringify(b)+"&s="+Math.floor(1E5*Math.random())+"&cv="+c;d.G(e,function(e){if(e){f=!0;window[c]=function(){};
for(var k in b)d.I(k,!1);a(b);a=function(){}}})}else a(b)};e.prototype.queueDisplay=function(b){var a=this.u(b);a||(a=b);"object"===typeof a&&setTimeout(function(){1>a.m.display&&a.display()},1500);return this.l.push(a)};e.prototype.getSlotByElementId=function(b){return this.u(b)};e.prototype.u=function(b){return this.i.hasOwnProperty(b)?this.i[b]:!1};e.prototype.w=function(b){return this.j.hasOwnProperty(b)?this.j[b]:!1};e.prototype.getSlotByKeymaker=function(b){return this.w(b)};e.prototype.setDisplayFunction=
function(b){c.setDisplay(b)};e.prototype.G=function(b,a){if(null!=b){null==a&&(a=function(){});try{var d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=b;if(a!=function(){}){var c=setTimeout(function(){try{a(!0)}catch(b){}a=function(){}},1500);d.readyState?d.onreadystatechange=function(){clearTimeout(c);if("loaded"==d.readyState||"complete"==d.readyState){d.onreadystatechange=null;try{a()}catch(b){}a=function(){}}}:d.onload=function(){clearTimeout(c);try{a()}catch(b){}a=
function(){}}}var f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(d,f)}catch(e){}}};e.prototype.getSlots=function(){return this.b};e.prototype.getLogger=function(){return this.c};e.prototype.getAllLogs=function(){return this.c.getLogs()};e.prototype.getLogBySlot=function(a){return this.c.getLogBySlot(a)};e.log=function(){};e.setLogger=function(a){c.setLogger(a.log.bind(a))};e.prototype.loadDebugger=function(a){this.G("//mtrx.go.sonobi.com/morpheusLog.debug.js",function(){window.console&&
"function"===typeof window.console.log&&console.log("LOADED DEBUG SCRIPT!");"function"===typeof a&&a()})};e.prototype.setSizes=function(a,c){var d=this.getSlotByElementId(a);d?d.setSizes(c):(this.o[a]=c,this.c.log(41,[a,c]))};e.prototype.setDisabledSlot=function(a){var c=this.getSlotByElementId(a);c?c.disable():(this.C.push(a),this.c.log(43,[a]))};e.prototype.removeSlots=function(a){a=a.map(function(a){return a.A});for(var c=[],d=0;d<this.b.length;d++)-1===a.indexOf(this.b[d].A)&&c.push(this.b[d]);
this.b=c;this.i={};this.j={};for(d=0;d<this.b.length;d++)this.i[this.b[d].v]=this.j[this.b[d].A]=this.b[d];return this.b};var a={ca:1500,K:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),Z:!1,D:[]};if(window[r]&&"object"===typeof window[r])for(var u in window[r])switch(u){case "cmd":a.D=window[r][u];break;case "acceptedSizes":a.K=window[r][u];break;case "timeout":a.ca=window[r][u]}a.version="2.2.2";a.ba=!1;a.P=!1;a.g=null;a.da=[];a.getManager=
function(){return a.g};a.R=function(){var b=a.g,c=a.a.f.enableServices;a.S=!1;a.a.f.enableServices=function(){a.log(10,["enableServices"]);a.S||(a.S=!0);return c.apply(this,arguments)};var d=a.a.h.enableSingleRequest;a.a.h.enableSingleRequest=function(){a.log(10,["enableSingleRequest"]);var b=d.apply(this,arguments);return a.ba=b};var e=a.a.h.disableInitialLoad;a.a.h.disableInitialLoad=function(){a.log(10,["disableInitialLoad"]);a.P=!0;return e.apply(this,arguments)};var f=a.a.f.defineOutOfPageSlot;
a.a.f.defineOutOfPageSlot=function(){var a=f.apply(this,arguments);b.addSlot(a);return a};var k=a.a.f.defineSlot;a.a.f.defineSlot=function(){var a=k.apply(this,arguments);b.addSlot(a);return a};var h=a.a.f.defineUnit;a.a.f.defineUnit=function(){var a=h.apply(this,arguments);b.addSlot(a);return a};var m=a.a.f.display;a.a.f.display=function(){var c=arguments,d=arguments[0],e=a.g.getSlotByElementId(d);a.log(31,[d],e);if(a.P)return a.log(33,[d],e),m.apply(this,c);if(d&&e&&e.getBidSet())return a.log(34,
[d],e),e.display();d&&e&&(e.getBidding()||e.getInitialChecked())?b.queueDisplay(d):(b.queueDisplay(d),b.getBidsForUnfetched.bind(b)(function(){a.log(35,[])}))};var p=a.a.f.destroySlots;a.a.f.destroySlots=function(d){var c=[],c=0===arguments.length?b.getSlots():d.map(function(a){return a.getMorpheusSlot()});b.removeSlots(c);return p.apply(a.a.f,arguments)};var y=a.a.h.refresh;a.a.h.refresh=function(){var d=[],c=arguments,e=0;if(0<arguments.length&&"[object Array]"===Object.prototype.toString.call(arguments[0])){e=
arguments[0].length;a.log(28,[e]);for(var f=0;f<arguments[0].length;f++){var g=arguments[0][f];g&&"function"===typeof g.getMorpheusSlot?d.push(g.getMorpheusSlot()):a.log(30,[g,f])}}else a.log(28,[0]),d=a.g.getSlots();b.F(d,function(){for(var b=0;b<d.length;b++)d[b].m.refresh++;a.log(29,[e]);y.apply(a.a.h,c)})}};a.$=function(){a.g=new e;var b=a.g.getLogger();a.log=b.log.bind(b);a.log(16,[]);a.a={};window.googletag=window.googletag||{};a.a.f=window.googletag;a.a.f.cmd=a.a.f.cmd||[];null!=googletag.cmd.length?
(a.log(17,[]),a.log(18,[]),a.log(19,[]),a.a.f.cmd.unshift(function(){a.a.h=googletag.pubads();a.g.initialize(window.googletag,a.K);a.R()})):("-1"!=function(){return a.a.f.getEventLog().getAllEvents().map(function(a){return a.getMessage().getMessageId()})}().indexOf(8)&&a.log(20,[]),a.a.f.cmd.push(function(){a.a.h=googletag.pubads();a.g.initialize(window.googletag,a.K);a.R();for(var b=a.a.h.getSlots(),d=0;d<b.length;d++)a.g.addSlot(b[d])}));a.aa();return a};a.aa=function(){var b=0,c=a.D.length;if(0<
a.D.length)for(a.log(37,[c]);0<a.D.length;){var d=a.D.shift();a.log(38,[b++,c]);try{d()}catch(e){}}};a.outputCypherLog=function(){a.Z=!0;window.hasOwnProperty("SbiDebug")?window.SbiDebug.outputLog():a.g.loadDebugger(function(){setTimeout(function(){window.SbiDebug.outputLog()},100)})};a.log=function(){};a.setSlotSizes=function(b,c){a.g.setSizes(b,c)};a.disableSlot=function(b){a.g.setDisabledSlot(b)};a.enableReactiveSizes=function(){a.log(39,["sbi_morpheus.enableReactiveSizes"])};a.callOperator=function(){a.log(39,
["sbi_morpheus.callOperator"])};a.register=function(){a.log(39,["sbi_morpheus.register"])};window[r]=a.$();(function(){"object"!=typeof JSON&&(JSON={});(function(){function b(a){return 10>a?"0"+a:a}function c(a){return f.lastIndex=0,f.test(a)?'"'+a.replace(f,function(a){var b=m[a];return"string"==typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,b){var e,f,g,m,q,n=k,l=b[a];switch(l&&"object"==typeof l&&"function"==typeof l.toJSON&&(l=l.toJSON(a)),"function"==
typeof p&&(l=p.call(b,a,l)),typeof l){case "string":return c(l);case "number":return isFinite(l)?l+"":"null";case "boolean":case "null":return l+"";case "object":if(!l)return"null";if(k+=h,q=[],"[object Array]"===Object.prototype.toString.apply(l)){m=l.length;for(e=0;m>e;e+=1)q[e]=d(e,l)||"null";return g=0===q.length?"[]":k?"[\n"+k+q.join(",\n"+k)+"\n"+n+"]":"["+q.join(",")+"]",k=n,g}if(p&&"object"==typeof p)for(m=p.length,e=0;m>e;e+=1)"string"==typeof p[e]&&(f=p[e],g=d(f,l),g&&q.push(c(f)+(k?": ":
":")+g));else for(f in l)Object.prototype.hasOwnProperty.call(l,f)&&(g=d(f,l),g&&q.push(c(f)+(k?": ":":")+g));return g=0===q.length?"{}":k?"{\n"+k+q.join(",\n"+k)+"\n"+n+"}":"{"+q.join(",")+"}",k=n,g}}"function"!=typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(a.valueOf())?a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=
Boolean.prototype.toJSON=function(){return a.valueOf()});var e,f,k,h,m,p;"function"!=typeof JSON.stringify&&(f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m={"\b":"\\b","    ":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=function(a,b,c){var e;if(k="",h="","number"==typeof c)for(e=0;c>e;e+=1)h+=" ";else"string"==typeof c&&(h=c);if(p=b,b&&"function"!=typeof b&&("object"!=typeof b||"number"!=
typeof b.length))throw Error("JSON.stringify");return d("",{"":a})});"function"!=typeof JSON.parse&&(e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,JSON.parse=function(a,b){function c(a,d){var e,f,g=a[d];if(g&&"object"==typeof g)for(e in g)Object.prototype.hasOwnProperty.call(g,e)&&(f=c(g,e),void 0!==f?g[e]=f:delete g[e]);return b.call(a,d,g)}var d;if(a+="",e.lastIndex=0,e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})),
/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),"function"==typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})();Object.keys||(Object.keys=function(){var a=Object.prototype.hasOwnProperty,c=!{toString:null}.propertyIsEnumerable("toString"),d="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),
e=d.length;return function(f){if("object"!==typeof f&&("function"!==typeof f||null===f))throw new TypeError("Object.keys called on non-object");var k=[],h;for(h in f)a.call(f,h)&&k.push(h);if(c)for(h=0;h<e;h++)a.call(f,d[h])&&k.push(d[h]);return k}}());Function.prototype.bind||(Function.prototype.bind=function(a){function c(){return f.apply(this instanceof d?this:a,e.concat(Array.prototype.slice.call(arguments)))}function d(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");
var e=Array.prototype.slice.call(arguments,1),f=this;return d.prototype=this.prototype,c.prototype=new d,c})})()})("sbi_morpheus");
//2.2.7