/*  PolyMorph - Client Side Cookie Syncing Integration script 
    - Cookie syncing with RTB & S2S demand partners
    - Smode : 3 (Server side cookie table)
    - Modes supported
        - Sync : Daisy Chain to partners
        - Async : Parallel calls to partners
**/
(function(CookieSync) {
    var pubUuid = null,
        pubNetworkId = null,
        subVersion = 1.0;

    // One sync pixel per partner
    // Ids are generated by polymorph after partner integration is complete
    dropS2SAsyncPixel = function(dspId, index) {
        var syncBaseUrl = "https://rudy.adsnative.com/cm.gif?smode=3",
            pxl = document.createElement('img');

        pxl.src = syncBaseUrl + '&pnid=' + pubNetworkId + '&puuid=' + pubUuid + '&dspid=' + dspId;
        pxl.width = pxl.height = 0;
        document.body.appendChild(pxl);
    }

    // One sync pixel chained to all partners
    dropDaisyChainPixel = function() {
        var syncBaseUrl = "https://rudy.adsnative.com/cm.gif?smode=3",
            pxl = document.createElement('img');

        pxl.src = syncBaseUrl + '&pnid=' + pubNetworkId + '&puuid=' + pubUuid;
        pxl.width = pxl.height = 0;
        document.body.appendChild(pxl);
    }

    setUUIDCookie = function(uuid) {
        var cookieName = '_uuid',
            expiryDate = new Date();

        document.cookie = cookieName +"=" + uuid + ";expires=" + expiryDate.setTime(expiryDate.getTime() + (5 * 60 * 1000)) + ";domain=.adsnative.com;path=/";
    }

    dropSyncIframe = function(iframePartner) {
        var ifrm = document.createElement("iframe");
        ifrm.setAttribute("src", iframePartner['src'].replace('[DSP-ID]', iframePartner['uuid']));
        ifrm.style.width = "0px";
        ifrm.style.height = "0px";
        ifrm.style.display = "none";
        ifrm.marginWidth = "0";
        ifrm.marginHeight = "0";
        ifrm.frameBorder = "0";
        ifrm.id = iframePartner['iframeId'];
        document.body.appendChild(ifrm);    
    }

    getNetworkObj = function(networkKey) {
        var networkMap = [{
            networkKey: '82372e12bed54dcdab1accf207bef821',
            networkId: '734',
            async: true,
            partnerIds: ['439436328', '1416370744', '159402804', '823634934', '635031100', '2147483647', '2015930208', '1162890136', '1378574299', '556869201', '2053112301', '1830491566', '503409700', '1125584507', '349348236', '47808144', '692015568'],
            iframePartners: [{
                    "src": "https://secure-assets.rubiconproject.com/utils/xapi/multi-sync.html?p=[DSP-ID]&endpoint=eu",
                    "uuid" : "polymorphbanner",
                    "iframeId": "multisync-iframe"
                }, {
                    "src": "https://secure-assets.rubiconproject.com/utils/xapi/multi-sync.html?p=[DSP-ID]&endpoint=eu",
                    "uuid" : "polymorphnative", // Rubicon uuid's were provided by : hdeodhar@rubiconproject.com
                    "iframeId": "multisync-iframe"
                }, {
                    "src" : "https://us-u.openx.net/w/1.0/cm?id=685373b7-c1db-447a-9762-2b4a7f721daf&ph=be70468f-ec25-4271-8f20-ecdfee125ece&r=https://rudy.adsnative.com/cm.gif?dspid=[DSP-ID]&smode=3&buid=",
                    "uuid": "872584351",
                    "iframeId": "openx-3-way-sync-iframe"
                }]
        }];

        for (var i = 0; i < networkMap.length; i++) {
            if (networkMap[i].networkKey === networkKey && networkMap[i].networkId) {
                return networkMap[i];
            }
        }
        return null;
    }

    CookieSync.init = function(uuid, networkKey) {
        pubNetworkObj = getNetworkObj(networkKey);
        if (!uuid || !pubNetworkObj.networkId) return;
        pubUuid = uuid;
        pubNetworkId = pubNetworkObj.networkId

        if (pubNetworkObj.async) {
            // Save UUID cookie for Rudy to access when redirect is received from JS based cookie sync partners (Eg : Rubicon DSP)
            setUUIDCookie(uuid);
            if(pubNetworkObj.partnerIds && pubNetworkObj.partnerIds.length)
                pubNetworkObj.partnerIds.forEach(dropS2SAsyncPixel);
            if(pubNetworkObj.iframePartners && pubNetworkObj.iframePartners.length)
                pubNetworkObj.iframePartners.forEach(dropSyncIframe);
        } else {
            dropDaisyChainPixel();
        }
    }

}(window.CookieSync = window.CookieSync || {}));
