/*  PolyMorph - Client Side Cookie Syncing Integration script 
    - Cookie syncing with RTB & S2S demand partners
    - Smode : 3 (Server side cookie table)
    - Modes supported
        - Sync : Daisy Chain to partners
        - Async : Parallel calls to partners
**/
(function(CookieSync) {
    var pubUuid = null,
        pubNetworkId = null,
        subVersion = 0.7;

    // One sync pixel per partner
    // Ids are generated by polymorph after partner integration is complete
    dropS2SAsyncPixel = function(dspId, index) {
        var syncBaseUrl = "https://rudy.adsnative.com/cm.gif?smode=3",
            pxl = document.createElement('img');

        pxl.src = syncBaseUrl + '&pnid=' + pubNetworkId + '&puuid=' + pubUuid + '&dspid=' + dspId;
        pxl.width = pxl.height = 0;
        document.body.appendChild(pxl);
    }

    // One sync pixel chained to all partners
    dropDaisyChainPixel = function() {
        var syncBaseUrl = "https://rudy.adsnative.com/cm.gif?smode=3",
            pxl = document.createElement('img');

        pxl.src = syncBaseUrl + '&pnid=' + pubNetworkId + '&puuid=' + pubUuid;
        pxl.width = pxl.height = 0;
        document.body.appendChild(pxl);
    }

    dropRubiconJSTag = function(rubiconPartnerId) {
        var ifrm = document.createElement("iframe");
        ifrm.setAttribute("src", "https://secure-assets.rubiconproject.com/utils/xapi/multi-sync.html?p="+ rubiconPartnerId +"&endpoint=eu");
        ifrm.style.width = "0px";
        ifrm.style.height = "0px";
        ifrm.style.display = "none";
        ifrm.marginWidth = "0";
        ifrm.marginHeight = "0";
        ifrm.frameBorder = "0";
        ifrm.id = "multisync-iframe";
        document.body.appendChild(ifrm);
    }    

    getNetworkObj = function(networkKey) {
        var networkMap = [{
            networkKey: '82372e12bed54dcdab1accf207bef821',
            networkId: '734',
            async: true,
            partnerIds: ['439436328', '1416370744', '159402804', '823634934', '635031100', '2147483647', '2015930208', '1162890136', '1378574299', '556869201', '2053112301', '1830491566', '503409700', '1125584507', '47808144'],
            rubiconPartnerIds: ['16660banner', '16660native']
        }];

        for (var i = 0; i < networkMap.length; i++) {
            if (networkMap[i].networkKey === networkKey && networkMap[i].networkId) {
                return networkMap[i];
            }
        }
        return null;
    }

    CookieSync.init = function(uuid, networkKey) {
        pubNetworkObj = getNetworkObj(networkKey);
        if (!uuid || !pubNetworkObj.networkId) return;
        pubUuid = uuid;
        pubNetworkId = pubNetworkObj.networkId

        if (pubNetworkObj.async) {
            if(pubNetworkObj.partnerIds && pubNetworkObj.partnerIds.length)
                pubNetworkObj.partnerIds.forEach(dropS2SAsyncPixel);
            if(pubNetworkObj.rubiconPartnerIds && pubNetworkObj.rubiconPartnerIds.length)
                pubNetworkObj.rubiconPartnerIds.forEach(dropRubiconJSTag);
        } else {
            dropDaisyChainPixel();
        }
    }

}(window.CookieSync = window.CookieSync || {}));
