(function(){function A(a,c){var b={};if("object"===typeof c.dataObject&&c.dataObject&&0<p.keys(c.dataObject).length)if("static"===c.scriptName){var f=d.extraData[a.hash]||[];f.push(c.dataObject);d.extraData[a.hash]=f}else b=c.dataObject;d.send(b,c.scriptName,null,a.hash,a.base)}if(!this.dimml){Array.prototype.indexOf||(Array.prototype.indexOf=function(a,c){if(void 0===this||null===this)throw new TypeError('"this" is null or not defined');var b=this.length>>>0;c=+c||0;Infinity===Math.abs(c)&&(c=0);
0>c&&(c+=b,0>c&&(c=0));for(;c<b;c++)if(this[c]===a)return c;return-1});var B={},x=Array.prototype,F=x.slice,G=x.splice,C=x.forEach,d={},p={has:function(a,c){return Object.prototype.hasOwnProperty.call(a,c)}};p.keys=Object.keys||function(a){if(a!==Object(a))throw new TypeError("Invalid object");var c=[],b;for(b in a)p.has(a,b)&&c.push(b);return c};p.each=function(a,c,b){if(null!=a)if(C&&a.forEach===C)a.forEach(c,b);else if(a.length===+a.length)for(var f=0,d=a.length;f<d&&c.call(b,a[f],f,a)!==B;f++);
else for(var h=p.keys(a),f=0,d=h.length;f<d&&c.call(b,a[h[f]],h[f],a)!==B;f++);};p.extend=function(a){p.each(F.call(arguments,1),function(c){if(c)for(var b in c)a[b]=c[b]});return a};d._=p;d.load=function(a,c){var b=document.createElement("script");b.type="text/javascript";b.readyState?b.onreadystatechange=function(){if("loaded"==b.readyState||"complete"==b.readyState)b.onreadystatechange=null,c()}:b.onload=function(){c()};b.src=a;document.getElementsByTagName("head")[0].appendChild(b)};d.rnd4=function(){return(Math.floor(1632959*
Math.random())+46656).toString(36)};(function(){function a(b){var c=Array.prototype.slice.call(arguments,1),a,e,r=c.length;for(e=0;e<r;e++)if(a=typeof b[c[e]],!/^(?:function|object|unknown)$/.test(a))return!1;return!0}function c(b,c){return function(a){c.call(d(b),a||window.event)}}function b(b,c){return function(a){if(q[b]&&q[b][c])for(var e=q[b][c],r=0,y=e.length;r<y;r++)e[r].call(this,a||window.event)}}var f=function(){if("undefined"!==typeof document.documentElement.uniqueID)return function(b){return b.uniqueID};
var b=0;return function(c){return c.__uniqueID||(c.__uniqueID="uniqueID__"+b++)}}(),d,h;(function(){var b={};d=function(c){return b[c]};h=function(c,a){b[c]=a}})();var l,n;l=a(document.documentElement,"addEventListener","removeEventListener")&&a(window,"addEventListener","removeEventListener");var t=a(document.documentElement,"attachEvent","detachEvent")&&a(window,"attachEvent","detachEvent"),u={},q={};l?(l=function(b,c,a){b.addEventListener(c,a,!1)},n=function(b,c){return b?"undefined"!==typeof b.addEventListener:
!1}):t?(l=function(b,a,d){var e=f(b);h(e,b);u[e]||(u[e]={});u[e][a]||(u[e][a]=[]);d={handler:d,wrappedHandler:c(e,d)};u[e][a].push(d);b.attachEvent("on"+a,d.wrappedHandler)},n=function(b,c){return b?"undefined"!==typeof b.attachEvent:!1}):(l=function(c,a,d){var e=f(c);q[e]||(q[e]={});if(!q[e][a]){q[e][a]=[];var r=c["on"+a];r&&q[e][a].push(r);c["on"+a]=b(e,a)}q[e][a].push(d)},n=function(b,c){return b?null!==b["on"+c]:!1});this.elementHandlesEvent=n;this.addEventListener=function(b){return function(c,
a,e){if(null!==c)if(c.jquery)c.bind(a,e);else if(n(c))b(c,a,e);else if("undefined"!==typeof c.length)for(var r=0;r<c.length;r++)c[r]&&b(c[r],a,e)}}(l)}).call(d);var D=function(a,c,b,f,g){d.safe(function(){var a=null;try{a=c()}catch(l){}return a&&(a.jquery&&0<a.length||!a.jquery&&dimml.elementHandlesEvent(a)||!a.jquery&&!dimml.elementHandlesEvent(a)&&"undefined"!==a.length&&0<a.length)?(d.addEventListener(a,b,f),!0):!1})||(5E3>a?setTimeout(function(){D(Math.pow(a,1.2),c,b,f,g)},Math.round(a)):"function"===
typeof g&&(d.log("wait: "+a),g()))};d.registerEventListener=function(a,c,b,d){D(10,a,c,b,d)};(function(){var a=document.getElementsByTagName("script"),c="cdn.dimml.io";if(a&&0<a.length)for(var b in a)a[b].src&&a[b].src.match(/\/dimml\.js$/)&&(c=a[b].src,c=c.substring(c.indexOf(":")+1,a[b].src.length-9));p.base=c;p.host=window.location.hostname})();d.host=function(){return p.host};d.base=function(){return p.base};var E={};d.functions=function(a){if("undefined"===typeof a||!a)return{};a=String(a);var c=
E[a]||{};return E[a]=c};d.send=function(a,c,b,f,g){if(d.host()){c||(c="dynamic");var h=!(6<=c.length&&"static"===c.substring(0,6));b||(b=d.environment?d.environment:"prod");f||(f=d.sha1("static"===c?d.host():d.rnd4()));var l=[],n=0;for(k in a)null!==a[k]&&(l[n++]=k+"="+encodeURIComponent(String(a[k])));g||(g=h?"function"!==typeof d.baseDynamic?d.base():d.baseDynamic():d.base());a=g+"/"+(c+"/"+f+("prod"===b?"":"-"+b))+".js";0<l.length&&(a=a+"?"+l.join("&"));d.load(a,function(){})}};d.extraData={};
var z={},w={};d.event=function(a,c,b){var f=z[a];b=b||"static";"static"!==b&&(b+="/"+d.rnd4());c={dataObject:c,scriptName:b};f?A(f,c):(f=w[a]||[],f.push(c),w[a]=f)};d.addEventHash=function(a,c){"object"!==typeof c&&(c={hash:c});if(p.has(z,a))return!1;z[a]=c;if(w[a]){var b=w[a],d;for(d in b)A(c,b[d]);delete w[a]}return!0};var v=function(a,c){if("object"===typeof a)for(var b=p.keys(a),d=p.keys(c),g=0,h=b.length;g<h;g++)if(a[b[g]]){if(!v(a[b[g]],c[b[g]]))return!1}else{if(0>d.indexOf(b[g]))return!1}else if("string"===
typeof a)if(a&&0>a.indexOf("*")){if(a!=c)return!1}else if(!(new RegExp((a+"").replace(RegExp("[.\\\\+*?\\[\\^\\]$(){}=!<>|:\\-]","g"),"\\$&").replace(/\\\*/g,".*").replace(/\\\?/g,"."),"g")).test(String(c)))return!1;return!0};d.match=function(){for(var a=0;a<arguments.length;a++){var c=arguments[a];if("function"!==typeof c||c()){var b;if(b="string"===typeof c){if("*"==c)b=!0;else{b=new d.uri(c);var f=new d.uri(String(window.location));b=b.protocol()&&!v(b.protocol(),f.protocol())||b.host()&&!v(b.host(),
f.host())||b.path()&&!v(b.path(),f.path())||b.query()&&!v(b.query(),f.query())||b.fragment()&&!v(b.fragment(),f.fragment())?!1:!0}b=!b}if(b||"object"===typeof c&&c instanceof RegExp&&!c.test(location.href))return!1}else return!1}return!0};d.ws=function(){for(var a="https:"===location.protocol?"wss:":"ws:",c=d.environment?d.environment:"prod",b,f,g=0;g<arguments.length;g++){var h=arguments[g];"function"===typeof h?f=h:"object"===typeof h&&(b=h)}b&&b.hash&&b.base?(a+=b.base+"/websocket/"+b.hash,"prod"!==
c&&(a+="-"+c),a+=".ws"):(b="function"===typeof d.baseDynamic?d.baseDynamic():d.base(),a+=b+"/websocket/?dimml.concept=//"+c+"@"+d.host());a=new WebSocket(a);f&&(a.onmessage=function(b){f(b.data)});return a};d.safe=function(a){try{return a()}catch(c){d.error(c)}};d.ready=function(){function a(b){if(!u){if(!h.body)return d(a);for(u=!0;b=q.shift();)d(b)}}function c(c){if(n||"load"===c.type||"complete"===h.readyState)b(),a()}function b(){n?(h.removeEventListener("DOMContentLoaded",c,!1),g.removeEventListener("load",
c,!1)):(h.detachEvent("onreadystatechange",c),g.detachEvent("onload",c))}function d(b,c){setTimeout(b,0<=+c?c:1)}var g=window,h=g.document,l=h.documentElement,n="addEventListener"in h,t=!1,u=!1,q=[];if("complete"===h.readyState)d(a);else if(n)h.addEventListener("DOMContentLoaded",c,!1),g.addEventListener("load",c,!1);else{h.attachEvent("onreadystatechange",c);g.attachEvent("onload",c);try{t=null==g.frameElement&&l}catch(r){}t&&t.doScroll&&function y(){if(!u){try{t.doScroll("left")}catch(H){return d(y,
50)}b();a()}}()}return function(b){u?d(b):q.push(b)}}();d.extend=function(){return p.extend.apply(this,G.call(arguments,0,0,d))};d.cookies={get:function(a){return(tmp=document.cookie.match(new RegExp(a+"=[\\-a-zA-Z0-9.()=|%/]+($|;)","g")))&&tmp[0]?decodeURIComponent(tmp[0].substring(a.length+1,tmp[0].length).replace(";",""))||null:null},set:function(a,c,b,f,g,h){cookie=[a+"="+encodeURIComponent(c)];b&&cookie.push("expires="+d.cookies.hoursToExpireDate(b));"undefined"!==typeof f&&(cookie.push("path="+
(f?f:"/")),g||(g=window.location.hostname),0<g.indexOf(".")&&cookie.push("domain="+g));h&&cookie.push("secure");return document.cookie=cookie.join("; ")},unset:function(a,c,b){d.cookies.get(a)&&d.cookies.set(a,"",-720,c,b)},hoursToExpireDate:function(a){if("NaN"==parseInt(a))return"";now=new Date;now.setTime(now.getTime()+36E5*parseInt(a));return now.toGMTString()},test:function(){d.cookies.set("b49f729efde9b2578ea9f00563d06e57","true");return"true"==d.cookies.get("b49f729efde9b2578ea9f00563d06e57")?
(d.cookies.unset("b49f729efde9b2578ea9f00563d06e57"),!0):!1}};(function(){function a(c){this.message=c}a.prototype=Error();a.prototype.name="InvalidCharacterError";this.btoa||(this.btoa=function(c){for(var b,d,g=0,h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",l="";c.charAt(g|0)||(h="=",g%1);l+=h.charAt(63&b>>8-g%1*8)){d=c.charCodeAt(g+=.75);if(255<d)throw new a("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|d}return l});this.atob||
(this.atob=function(c){c=c.replace(/=+$/,"");if(1==c.length%4)throw new a("'atob' failed: The string to be decoded is not correctly encoded.");for(var b=0,d,g,h=0,l="";g=c.charAt(h++);~g&&(d=b%4?64*d+g:g,b++%4)?l+=String.fromCharCode(255&d>>(-2*b&6)):0)g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(g);return l})})();(function(){var a,c,b,f,g,h,l,n,t,u={}.hasOwnProperty;t="protocol username password host port path query fragment".split(" ");l=function(b){var c={},a,d,
e;if(!b)return c;a=b.indexOf(":");0>a&&(a=0);"//"!==b.substring(0,2)&&0<a&&(c.protocol=b.substring(0,a++));"//"===b.substring(a,a+2)&&(d=b.slice(a+2).search(/[\/\?#]/),0>d&&(d=b.length-a-2),e=b.slice(a+2,a+2+d),0<=e.indexOf("@")&&(c.username=decodeURIComponent(e.substring(0,e.indexOf("@"))),e=e.substring(e.indexOf("@")+1)),0<=e.indexOf(":")&&(c.port=Number(e.substring(e.indexOf(":")+1)),e=e.substring(0,e.indexOf(":"))),c.host=decodeURIComponent(e),a=a+2+d);a<b.length&&"?"!==b.substring(a,a+1)&&"#"!==
b.substring(a,a+1)&&(d=b.slice(a).search(/[\?#]/),0>d&&(d=b.length-a),c.path=decodeURIComponent(b.substring(a,a+d)),a+=d);"?"===b.substring(a,a+1)&&(d=b.indexOf("#",a),0>d&&(d=b.length),c.query=b.substring(a+1,d),a=d);"#"===b.substring(a,a+1)&&(c.fragment=decodeURIComponent(b.substring(a+1)));return c};g=function(b){return"[object Array]"===Object.prototype.toString.call(b)};h=function(b){return"[object Object]"===Object.prototype.toString.call(b)&&"object"===typeof b};f=function(b,a){var c,d;for(c in a)u.call(a,
c)&&(d=a[c],b[c]=d)};n=function(b){var a,c,d,e,m,f,q;c=/\[([^\]]*)\]/;a={};q=b.split("&");b=0;for(f=q.length;b<f;b++){d=q[b];e=d.split("=");d=e[0];m=e[1];e=c.exec(d);if(m)try{m=decodeURIComponent(m)}catch(I){}e?(e[1]&&!h(a[d])?a[d]={}:g(a[d])||(a[d]=[]),e[1]?a[d][e[1]]=m:a[d].push(m)):a[d]=m}return a};b=function(b,a){var c,d,e,m;if(!g(a)&&!h(a))return""+b+"="+encodeURIComponent(a);t=[];if(g(a))for(e=0,m=a.length;e<m;e++)c=a[e],t.push(""+b+"[]="+encodeURIComponent(c));if(h(a))for(d in a)u.call(a,d)&&
(c=a[d],t.push(""+b+"["+d+"]="+encodeURIComponent(c)));return t.join("&")};c="/";"undefined"!==typeof window&&null!==window&&window.location.host&&(c=window.location.href);a=function(){function a(a){this.uri=null!=a?a:c;this.parts=l(this.uri);this.parts.query=this.parts.query?n(this.parts.query):{}}a.prototype.retrieve=function(a,b){null==b&&(b=null);if(null===b)return this.parts[a];this.parts[a]=b;return this};a.prototype.protocol=function(a){return this.retrieve("protocol",a)};a.prototype.username=
function(a){return this.retrieve("username",a)};a.prototype.password=function(a){return this.retrieve("password",a)};a.prototype.host=function(a){return this.retrieve("host",a)};a.prototype.port=function(a){return this.retrieve("port",a)};a.prototype.path=function(a){return this.retrieve("path",a)};a.prototype.query=function(a,b){return a&&"string"===typeof a?b?(this.parts.query[a]=b,this):this.parts.query[a]:h(a)?(f(this.parts.query,a),this):this.parts.query};a.prototype.fragment=function(a){return this.retrieve("fragment",
a)};a.prototype.toString=function(){var a,c,d,e,m;d="";this.parts.protocol&&this.parts.host&&(d+=""+this.parts.protocol+"://",this.parts.username&&this.parts.password?d+=""+this.parts.username+":"+this.parts.password+"@":this.parts.username&&(d+=""+this.parts.username+"@"),d+=this.parts.host,this.parts.port&&(d+=":"+this.parts.port));d+=this.parts.path;c=[];m=this.parts.query;for(a in m)u.call(m,a)&&(e=m[a],c.push(b(a,e)));0<c.length&&(d+="?"+c.join("&"));this.parts.fragment&&(d+="#"+this.parts.fragment);
return d};return a}();d.uri=a})();(function(){var a=a||function(a,b){var c={},d=c.lib={},h=function(){},l=d.Base={extend:function(a){h.prototype=this;var b=new h;a&&b.mixIn(a);b.hasOwnProperty("init")||(b.init=function(){b.$super.init.apply(this,arguments)});b.init.prototype=b;b.$super=this;return b},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var b in a)a.hasOwnProperty(b)&&(this[b]=a[b]);a.hasOwnProperty("toString")&&(this.toString=
a.toString)},clone:function(){return this.init.prototype.extend(this)}},n=d.WordArray=l.extend({init:function(a,c){a=this.words=a||[];this.sigBytes=c!=b?c:4*a.length},toString:function(a){return(a||u).stringify(this)},concat:function(a){var b=this.words,c=a.words,d=this.sigBytes;a=a.sigBytes;this.clamp();if(d%4)for(var e=0;e<a;e++)b[d+e>>>2]|=(c[e>>>2]>>>24-e%4*8&255)<<24-(d+e)%4*8;else if(65535<c.length)for(e=0;e<a;e+=4)b[d+e>>>2]=c[e>>>2];else b.push.apply(b,c);this.sigBytes+=a;return this},clamp:function(){var b=
this.words,c=this.sigBytes;b[c>>>2]&=4294967295<<32-c%4*8;b.length=a.ceil(c/4)},clone:function(){var a=l.clone.call(this);a.words=this.words.slice(0);return a},random:function(b){for(var c=[],d=0;d<b;d+=4)c.push(4294967296*a.random()|0);return new n.init(c,b)}}),t=c.enc={},u=t.Hex={stringify:function(a){var b=a.words;a=a.sigBytes;for(var c=[],d=0;d<a;d++){var e=b[d>>>2]>>>24-d%4*8&255;c.push((e>>>4).toString(16));c.push((e&15).toString(16))}return c.join("")},parse:function(a){for(var b=a.length,
c=[],d=0;d<b;d+=2)c[d>>>3]|=parseInt(a.substr(d,2),16)<<24-d%8*4;return new n.init(c,b/2)}},q=t.Latin1={stringify:function(a){var b=a.words;a=a.sigBytes;for(var c=[],d=0;d<a;d++)c.push(String.fromCharCode(b[d>>>2]>>>24-d%4*8&255));return c.join("")},parse:function(a){for(var b=a.length,c=[],d=0;d<b;d++)c[d>>>2]|=(a.charCodeAt(d)&255)<<24-d%4*8;return new n.init(c,b)}},r=t.Utf8={stringify:function(a){try{return decodeURIComponent(escape(q.stringify(a)))}catch(m){throw Error("Malformed UTF-8 data");
}},parse:function(a){return q.parse(unescape(encodeURIComponent(a)))}},p=d.BufferedBlockAlgorithm=l.extend({reset:function(){this._data=new n.init;this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=r.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(b){var c=this._data,d=c.words,e=c.sigBytes,f=this.blockSize,g=e/(4*f),g=b?a.ceil(g):a.max((g|0)-this._minBufferSize,0);b=g*f;e=a.min(4*b,e);if(b){for(var h=0;h<b;h+=f)this._doProcessBlock(d,h);h=d.splice(0,b);c.sigBytes-=
e}return new n.init(h,e)},clone:function(){var a=l.clone.call(this);a._data=this._data.clone();return a},_minBufferSize:0});d.Hasher=p.extend({cfg:l.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){p.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);return this._doFinalize()},blockSize:16,_createHelper:function(a){return function(b,c){return(new a.init(c)).finalize(b)}},_createHmacHelper:function(a){return function(b,
c){return(new v.HMAC.init(a,c)).finalize(b)}}});var v=c.algo={};return c}(Math);(function(){var c=a,b=c.lib,d=b.WordArray,g=b.Hasher,h=[],b=c.algo.SHA1=g.extend({_doReset:function(){this._hash=new d.init([1732584193,4023233417,2562383102,271733878,3285377520])},_doProcessBlock:function(a,b){for(var c=this._hash.words,d=c[0],f=c[1],g=c[2],l=c[3],n=c[4],e=0;80>e;e++){if(16>e)h[e]=a[b+e]|0;else{var m=h[e-3]^h[e-8]^h[e-14]^h[e-16];h[e]=m<<1|m>>>31}m=(d<<5|d>>>27)+n+h[e];m=20>e?m+((f&g|~f&l)+1518500249):
40>e?m+((f^g^l)+1859775393):60>e?m+((f&g|f&l|g&l)-1894007588):m+((f^g^l)-899497514);n=l;l=g;g=f<<30|f>>>2;f=d;d=m}c[0]=c[0]+d|0;c[1]=c[1]+f|0;c[2]=c[2]+g|0;c[3]=c[3]+l|0;c[4]=c[4]+n|0},_doFinalize:function(){var a=this._data,b=a.words,c=8*this._nDataBytes,d=8*a.sigBytes;b[d>>>5]|=128<<24-d%32;b[(d+64>>>9<<4)+14]=Math.floor(c/4294967296);b[(d+64>>>9<<4)+15]=c;a.sigBytes=4*b.length;this._process();return this._hash},clone:function(){var a=g.clone.call(this);a._hash=this._hash.clone();return a}});c.SHA1=
g._createHelper(b);c.HmacSHA1=g._createHmacHelper(b)})();d.sha1=function(c){return a.SHA1(c).toString()}})();(function(){var a=function(a){setTimeout(function(){throw"DimML caught exception (missing console): "+a;},0)},c=function(a,b){if("function"===typeof a)return function(){a.apply(b,arguments)};if("object"===typeof a)return function(b){a(b)}},b=window.console||{};d.log=b.log?c(b.log,b):a;d.debug=b.debug?c(b.debug,b):b.log?d.log:a;d.info=b.info?c(b.info,b):b.log?d.log:a;d.warn=b.warn?c(b.warn,
b):b.log?d.log:a;d.error=b.error?c(b.error,b):b.log?d.log:a})();d.reload=function(){d.send({},"static")};(function(){var a=new d.uri(window.location.href),c=a.query("dimml.concept"),b="",f=null;"undefined"!==typeof c&&c&&(c=new d.uri(c),b=c.username(),c.host()&&(f=d.sha1(c.host())));b||(b=a.query("dimml"),"undefined"!==typeof b&&b?d.cookies.set("dimml",b,null,"/"):(b=d.cookies.get("dimml"),"undefined"!==typeof b&&b||(b="prod")));"prod"!=b&&d.info("DimML development mode: "+b);d.environment=b;d.send({},
"static",b,f)})();this.dimml=d}}).call(this);